language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
  - pip install pylint
install:
  - pip install -r requirements.txt # install package + test dependencies
script:
  # python -m unittest discover -s tests -p "test_*.py" # run tests
  - coverage run -m unittest discover -s tests -p "test_*.py" # run coverage
   # getting percentage from coveralls
  - pylint department-manager
after_success:
  - COVERALLS_REPO_TOKEN=dbLTzdOjosns0Avlrld8R5FXi0AbvOK4p coveralls # submit and get result